### ISSUE TITLE
In-memory revision guard and retry (random) timeout issue

### ISSUE THREAD

**Issue by OrH** [adrai/node-cqrs-saga#45]
Hey,

I think that there is an issue in a situation when a domain emits two events and a saga service that handles those events is using an in-memory revision guard store.

If the saga service is restarted and, for example, Event1 with revision 5 and Event2 with revision 6 are emitted together (from the domain), the saga's revision guard goes into the retry loop (because no older revision is found and the revision is > 1).
In the retry timeout, it randoms the milliseconds, so it's possible that Event2 with revision 6 will get smaller milliseconds and will eventually be handled before Event1.

What if the retry timeout would not random the milliseconds and it will maybe use the revision in the event somehow? Wouldn't it ensure that a bigger revision will still be handled after a smaller one if they came together?

Thanks,
Or

**Comment by nanov** [comment]
First of all, in-memory guard store is definitely not a production solution, memory will run out at one point. 

Second, i don't really get the point, do you have a test case to demonstrate a problem, because of the single-threaded nature of nodeJs, things don't happen in parallel but rather concurrently, this means that one event will be handled before the other even if they come in the exact same time.

**Comment by OrH** [comment]
Regarding the in-memory guard store in production, you are correct, this should not be used in production.

I can create a test case later today, but even though it's single threaded, if the event with revision 5 gets a timeout of 5 seconds and the event with revision 6 gets timeout of 1 second (because it's random), the event with revision 6 will get handled first and the event with revision 5 will get a revision handled error.

**Comment by nanov** [comment]
First to clarify, i am not 100% that this is what will happen, but assuming thats the case.

If i get you right, event 6 will fire an events missing event, and you will handle all the missing events including 5. And your concern is that 5 will get an AlreadyHandled error ?

If that's the case then i don't see a real problem here as all the events get handled accordingly, ie. one can ignore the AlredayHandled error.

If you provide an isolated test case, i would be more than happy to inspect it, and if needed implement a fix.

**Comment by OrH** [comment]
Thanks again @nanov , I forgot about the handle missing events function. Thanks
